# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.require_plugin "my_vagrant_plugin"

Vagrant::Config.run do |config|
  config.vm.box = "bentos/centos-6.7"

  # config.vm.network "forwarded_port", guest: 80, host: 8080  
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.synced_folder "./shared", "/home/vagrant/shared"

end